name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v

      - name: Checkout node modules
        with:
          node-version-file: ".nvmrc"

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npm run test
